# Generated by Django 3.2.7 on 2021-12-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
    ]
